### PR TITLE
Favor order in React components' members

### PR DESCRIPTION
**Pull request by Soreine**
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md

### CODE REVIEW

**Comment by SamyPesse** [comment]
@Soreine 👍  Does it support `eslint --fix` ?

**Comment by Soreine** [comment]
Not `eslint --fix` but:

> Fixable: This rule is automatically fixable using the [`sort-comp` transform](https://github.com/reactjs/react-codemod/blob/master/transforms/sort-comp.js) in [react-codemod](https://www.npmjs.com/package/react-codemod).

That's why I suggest a warning level. We could run the `react-codemod` script though, I did it once for `prop-types`...

**Comment by SamyPesse** [comment]
@Soreine take a look at the unit tests ;)

**Comment by zhouzi** [comment]
This is being addressed in #5 🎉

**Pull request closed without merging**
